[colors]
foreground = dce5dc
background = 0d1510
alpha = 0.7
blur = yes

# Regular colors
regular0 = 2e3731
regular1 = ffb4ab
regular2 = 47f4aa
regular3 = ffd0ab
regular4 = 98d3b1
regular5 = 006c46
regular6 = 859589
regular7 = bacbbe

# Bright colors
bright0 = 3c4a41
bright1 = 93000a
bright2 = 0bd790
bright3 = ffaa5e
bright4 = 185338
bright5 = dce5dc
bright6 = 3c4a41
bright7 = dce5dc
