pragma Singleton
import QtQuick
import Quickshell

Singleton {
	id: root

	// ---- Colors ----
	// Material palette generated by matugen into matugen-colors.qml
	// (see ~/.config/matugen/templates/quickshell-colors.qml). Values below
	// fall back to the previous hardcoded theme until the file exists.
	property var mpalette: null

	function loadPalette() {
		const comp = Qt.createComponent(Quickshell.shellDir + "/matugen-colors.qml")
		if (comp.status === Component.Ready) {
			root.mpalette = comp.createObject()
		} else if (comp.status === Component.Error) {
			console.warn("matugen palette unavailable:", comp.errorString())
		} else {
			comp.statusChanged.connect(() => {
				if (comp.status === Component.Ready) {
					root.mpalette = comp.createObject()
				} else if (comp.status === Component.Error) {
					console.warn("matugen palette unavailable:", comp.errorString())
				}
			})
		}
	}

	function withAlpha(c, a) {
		if (c === null || c === undefined)
			return Qt.rgba(0, 0, 0, 0)
		return Qt.rgba(c.r, c.g, c.b, a)
	}

	// Avatar/profile-picture images are square-ish; real large media
	// (screenshots, video thumbnails) is clearly landscape. Only the latter
	// should render as a big body image below the text — a plain "tall enough"
	// check misfires on big square avatars (Discord's 256x256 default, etc.).
	function isBigImage(w, h) {
		return w > h * 1.2 && h > 160
	}

	Component.onCompleted: root.loadPalette()

	readonly property color background: root.mpalette ? root.mpalette.background : "#111416"
	readonly property color text: root.mpalette ? root.mpalette.text : "#e2e2e5"
	readonly property color primary: root.mpalette ? root.mpalette.primary : "#9ccdee"
	readonly property color secondary: root.mpalette ? root.mpalette.secondary : "#b6c9d8"
	readonly property color accent: root.mpalette ? root.mpalette.accent : "#3b6d8b"
	readonly property color activeWorkspace: root.mpalette ? root.mpalette.activeWorkspace : "#ffffff"
	readonly property color critical: root.mpalette ? root.mpalette.critical : "#f53c3c"
	readonly property color barBackground: root.mpalette
		? root.withAlpha(root.mpalette.background, 0.5)
		: Qt.rgba(50 / 255, 50 / 255, 50 / 255, 0.5)

	// ---- Font ----
	readonly property string fontFamily: "JetBrainsMono Nerd Font"
	readonly property int pixelSize: 12

	// ---- Panel geometry (matches waybar) ----
	readonly property int barWidth: 30
	readonly property int barRadius: 7
	readonly property int barBorderWidth: 2
	readonly property int barMarginTop: 5
	readonly property int barMarginRight: 4
	readonly property int barMarginBottom: 5
	readonly property int moduleSpacing: 8
	readonly property int modulePaddingH: 3
	readonly property int modulePaddingV: 4
	// Vertical padding between the bar's top/bottom edge and the module
	// groups (also where the hover highlight starts/stops).
	readonly property int barPaddingV: 10
	readonly property int iconHeight: 20

	// ---- Popups (notification center / quick settings / mpris detail) ----
	readonly property int popupWidth: 320
	readonly property int popupMaxHeight: 520
	readonly property int popupRadius: 14
	readonly property color popupBackground: root.mpalette
		? root.withAlpha(root.mpalette.background, 0.5)
		: Qt.rgba(17 / 255, 20 / 255, 22 / 255, 0.5)
	readonly property color popupBorder: primary
	readonly property int popupBorderWidth: 1
	readonly property color cardBackground: root.mpalette
		? root.withAlpha(root.mpalette.text, 0.07)
		: Qt.rgba(255 / 255, 255 / 255, 255 / 255, 0.07)
	readonly property color cardBackgroundHover: root.mpalette
		? root.withAlpha(root.mpalette.text, 0.14)
		: Qt.rgba(255 / 255, 255 / 255, 255 / 255, 0.14)
	// Toasts are more opaque than the popup panels so their text stays readable
	// over busy wallpapers.
	readonly property color toastBackground: root.mpalette
		? root.withAlpha(root.mpalette.background, 0.9)
		: Qt.rgba(17 / 255, 20 / 255, 22 / 255, 0.9)
	readonly property color toggleOn: primary
	readonly property color toggleOff: root.mpalette
		? root.withAlpha(root.mpalette.text, 0.15)
		: Qt.rgba(255 / 255, 255 / 255, 255 / 255, 0.15)

	// ---- Animation (smooth / fluid) ----
	readonly property int animShort: 150
	readonly property int animMedium: 250
	readonly property int animLong: 400
	readonly property int animDropdown: 300
}
