env = AQ_DRM_DEVICES,/dev/dri/card2:/dev/dri/card1

# Nvidia settings for apps
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GBM_BACKEND,nvidia-drm

# Required for some setups to prevent freezing
env = WLR_NO_HARDWARE_CURSORS,1
